version: "3.3"
services:
  frontend:
    build: frontend/
    image: alexcaley/frontend_website:latest
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
  backend:
    build: backend/
    image: alexcaley/backend_website:latest
    ports:
      - "127.0.0.1:4000:4000"
    restart: always
