version: "3.3"
services:
  frontend:
    build: frontend/
    container_name: portfolio_frontend
    image: alexcaley/frontend_website:1.4
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
  backend:
    build: backend/
    container_name: portfolio_backend
    image: alexcaley/backend_website:1.0.3
    ports:
      - "127.0.0.1:4000:4000"
    restart: always
